module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: ({colors}) => ({
        slate: colors.slate,
        black: colors.black,
        teal: {
          brand: '#00ADB5',
          50: colors.teal[50],
          100: colors.teal[100],
          200: colors.teal[200],
          300: colors.teal[300],
          400: colors.teal[400],
          500: colors.teal[500],
          600: colors.teal[600],
          700: colors.teal[700],
          800: colors.teal[800],
          900: colors.teal[900],
          950: colors.teal[950],
        },
        app: {
          dark: '#161A30',
          black: '#222831',
          light: '#B6BBC4',
          primary: '#31304D',
          offwhite: '#F0ECE5',
        },
        'dark-gray': '#393E46',
        gray: colors.gray,
        purple: colors.purple,
        inherit: colors.inherit,
        current: colors.current,
        transparent: colors.transparent,
        white: colors.white,
        zinc: colors.zinc,
        neutral: colors.neutral,
        stone: colors.stone,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      }),
    },
  },
  plugins: [],
  corePlugins: require('tailwind-rn/unsupported-core-plugins'),
};
